// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: piefiredie.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BeefClient is the client API for Beef service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BeefClient interface {
	BeefSummary(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type beefClient struct {
	cc grpc.ClientConnInterface
}

func NewBeefClient(cc grpc.ClientConnInterface) BeefClient {
	return &beefClient{cc}
}

func (c *beefClient) BeefSummary(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/backendChallenge.Beef/BeefSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeefServer is the server API for Beef service.
// All implementations must embed UnimplementedBeefServer
// for forward compatibility
type BeefServer interface {
	BeefSummary(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedBeefServer()
}

// UnimplementedBeefServer must be embedded to have forward compatible implementations.
type UnimplementedBeefServer struct {
}

func (UnimplementedBeefServer) BeefSummary(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeefSummary not implemented")
}
func (UnimplementedBeefServer) mustEmbedUnimplementedBeefServer() {}

// UnsafeBeefServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BeefServer will
// result in compilation errors.
type UnsafeBeefServer interface {
	mustEmbedUnimplementedBeefServer()
}

func RegisterBeefServer(s grpc.ServiceRegistrar, srv BeefServer) {
	s.RegisterService(&Beef_ServiceDesc, srv)
}

func _Beef_BeefSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeefServer).BeefSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backendChallenge.Beef/BeefSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeefServer).BeefSummary(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Beef_ServiceDesc is the grpc.ServiceDesc for Beef service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Beef_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "backendChallenge.Beef",
	HandlerType: (*BeefServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeefSummary",
			Handler:    _Beef_BeefSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "piefiredie.proto",
}
